// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB461G_HxYQNWDO-4q0OYDYKfo43J9we5k',
    appId: '1:968471835515:web:260363b4fc08bed681c3de',
    messagingSenderId: '968471835515',
    projectId: 'kesehatan-mental-anak-remaja',
    authDomain: 'kesehatan-mental-anak-remaja.firebaseapp.com',
    storageBucket: 'kesehatan-mental-anak-remaja.appspot.com',
    measurementId: 'G-QNPZZRNWXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC67ScuUAcDXyZv2FPv8O15GWrOZXtpV9I',
    appId: '1:968471835515:android:695162148225288e81c3de',
    messagingSenderId: '968471835515',
    projectId: 'kesehatan-mental-anak-remaja',
    storageBucket: 'kesehatan-mental-anak-remaja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ9OJgTW6rPbllAg6Zdwm_FM-TJU4PePM',
    appId: '1:968471835515:ios:b0d48fff0292a50581c3de',
    messagingSenderId: '968471835515',
    projectId: 'kesehatan-mental-anak-remaja',
    storageBucket: 'kesehatan-mental-anak-remaja.appspot.com',
    iosBundleId: 'com.example.aplikasiKesehatanMentalAnakRemaja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ9OJgTW6rPbllAg6Zdwm_FM-TJU4PePM',
    appId: '1:968471835515:ios:d619d54ee5ffd58381c3de',
    messagingSenderId: '968471835515',
    projectId: 'kesehatan-mental-anak-remaja',
    storageBucket: 'kesehatan-mental-anak-remaja.appspot.com',
    iosBundleId: 'com.example.aplikasiKesehatanMentalAnakRemaja.RunnerTests',
  );
}
